### PR TITLE
Update style.css

### PR DESCRIPTION
**Pull request by AmanSingh81757**
- The go to top button had hover effect even when not active (i.e when we the page is at the top). 
- Fixed by adding the hover effect and cursor pointer effect only when the button is active.

Can't add screenshot as the cursor isn't visible in screenshots.

Improvement on PR #547

### CODE REVIEW

**Comment by AmanSingh81757** [comment]
@tombruijn hello, could you please review this PR and merge if no conflicts are found.

**Comment by tombruijn** [comment]
I think we should hide the button better. Like `display: none` by default for the `.go-to-top-arrow` class, or some `visibility: hidden` property, which then gets changed on hover.

Otherwise it is still there, only less apparent it's there, and could still get in the way.

**Comment by tombruijn** [comment]
@AmanSingh81757 do you want try those two options? Either `display: none` or `visibility: hidden`.

**Comment by AmanSingh81757** [comment]
> @AmanSingh81757 do you want try those two options? Either `display: none` or `visibility: hidden`.

I changed the css a bit to use the display property to hide the button when inactive and display it when scrolled down

**Comment by AmanSingh81757** [comment]
@tombruijn  I did the recommended changes could you merge the PR now

**Pull request merged**
